requirements.txt, setup.py, tiledbcontents/tiledbcontents.py
During notebook startup we are observing up to 3 requests being made for listing categories/namespaces within rapid succession. This causes delays in starting the environment so we'll cache a notebook listing if it is within the last 4 seconds.
=> Cache listing requests for namespace/categories

tiledbcontents/tiledbcontents.py
If the env variables are set for the image name or size tags we'll add those on notebook creation.
=> Add support for image name/size tags from env

requirements.txt, setup.py, tiledbcontents/tiledbcontents.py
TileDB Cloud Arrays now have file type and file properties which allow for better and more robust handling of special types like the notebook files.
=> Switch notebooks from tags to file properties

requirements.txt, setup.py
This dependency is missing upstream so on fresh clean installations sometimes the plugin fails to install with nose missing. We add it here to improve the user installation experience.
=> Jupyterlab itself has a dependency on nose

tiledbcontents/tiledbcontents.py
This prevents from creating a large number of contexts which have to be cleaned up and might cause thread contention if a large number of notebooks are opened.
=> Use one global context for TileDB

tiledbcontents/tiledbcontents.py
The jupyterlab contents API spec indicates that the format should only be set if the contents is being asked for. This prevents 500 errors on listing without content request.
=> Format must only be returned if contents requests

tiledbcontents/tiledbcontents.py
The python GC will take care of this, but if we close right away resources are freed faster. This is just an optimization.
=> Close array to clear resources

tiledbcontents/tiledbcontents.py
This prevents a 500 error where we tried to iterate over None.
=> Handle None from cloud listings

requirements.txt, setup.py, tiledbcontents/tiledbcontents.py
Store notebooks as a dense array now that TileDB-Py 0.7 with TileDB 2.1 is out.
=> Store notebooks as a dense array

tiledbcontents/tiledbcontents.py
We should always list all organizations and namespaces a user is part of in "owned" folder listing. Current behavior was that as soon as one namespace created a notebook we'd only list that on. The change makes it so we always build the base list of namespaces in the owned category.
=> All user namespaces should be listed in owned

tiledbcontents/tiledbcontents.py
Error opening notebook cloud/shared/seth/Rady-HPO-Example: HTTP 400: Bad Request (Error fetching notebook: ‘utf-8’ codec can’t decode byte 0xd7 in position 8556: invalid continuation byte)
Available choices for second argument
(https://docs.python.org/3/howto/unicode.html)
```
>>> b'\x80abc'.decode("utf-8", "strict")  
Traceback (most recent call last):
...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0:
invalid start byte
>>> b'\x80abc'.decode("utf-8", "replace")
'\ufffdabc'
>>> b'\x80abc'.decode("utf-8", "backslashreplace")
'\\x80abc'
>>> b'\x80abc'.decode("utf-8", "ignore")
'abc'
```
=> Replaces invalid utf-8 chars with backslash when decoding file contents

tiledbcontents/ipycompat.py, tiledbcontents/tiledbcontents.py
- Sort imports
- Replace `some_str is "something"` with `some_str == "something"`
- Remove unreachable code and unused vars
- Fix up format strings
I don’t *think* this will make it possible to upload a notebook into a cloud folder, but it is some stuff that should probably happen.
=> Clean up some lints in tiledbcontents.

requirements.txt, setup.py, tiledbcontents/caching.py, tiledbcontents/paths.py, tiledbcontents/tiledbcontents.py
This branch, best reviewed commit-by-commit (it’s not as scary as it looks!), starts to break up the monolithic tiledbcloudcontents.py file into a few more cohesive modules, along with a few other cleanups. More details are found in each commit, but in broad strokes, it:
- Simplifies use and comparison of datetimes
- Removes unused code
- Pulls caching and path manipulation out into their own modules (`caching.py` and `paths.py`, respectively).
=> Start to modularize tiledbcontents.

tiledbcontents/arrays.py, tiledbcontents/caching.py, tiledbcontents/listings.py, tiledbcontents/models.py, tiledbcontents/paths.py, tiledbcontents/tiledbcontents.py
Yes, it’s another cleanup change, once again best read one commit as a time.
Overall, this separates the code into:
- arrays.py, which deals directly with the reading and writing of arrays
- listings.py, which deals with file lists
- models.py, which has mostly a few leftovers that are used when creating or manipulating models
It also adds a few more things into paths.py and performs an assortment of other related cleanups along the way.
After this change, all of what remains in the various `ContentManager` classes is only the stuff that actually depends on other things within the `ContentsManager`, with no methods that are completely independent of the instance’s state (i.e., there are no methods which don’t use `self`), and tiledbcontents.py contains essentially only the code that is …
=> More (the last?) cleanup and modularization of tiledbcontents.

tiledbcontents/arrays.py, tiledbcontents/caching.py, tiledbcontents/tiledbcontents.py
This change fixes the bug that prevented us from uploading Jupyter
notebooks even after we stopped treating them like other files.
- Creates a `tiledb:is_new` field on the model when creating a new
notebook, so we know when a notebook is, uh, new.
- Puts all TileDB-specific variables in a `tiledb:` namespace on the
model to avoid potential collisions.
- Minor cleanups.
Also fixes a bug where we would never fetch new directory listings after startup.
=> Add support for uploading notebooks to TileDB Cloud (!)

tiledbcontents/tiledbcontents.py
Commit cd17208815e3eb7cf31fb6120272341439dac35c introduced a regression
where, because creating notebooks in local storage did not try to
increment the filename, a new untitled file would end up overwriting
an existing file of the same name rather than creating, e.g.
"Untitled-2".
This change restores the name-incrementation step for newly-created
local files.
=> Increment the filename when creating new local files.

tiledbcontents/tiledbcontents.py
In this change:
https://github.com/TileDB-Inc/TileDB-Cloud-Py/commit/496ccb21c59c344e1540a1650b95c2feae84f788
we removed the unnecessary content-type parameter from the
`delete_array` function. We also have to update this call site.
=> Remove obsolete content-type parameter from `delete_array`.

tiledbcontents/listings.py, tiledbcontents/tiledbcontents.py
When attempting to serve a directory within JupyterLab (Hub?),
the `notebook` package unconditionally attempts to set a `Last-Modified`
header based on the `last_modified` key in the directory model.
This would fail if we served a directory which we did not have
`Last-Modified` info for:
Traceback (most recent call last):
File ".../site-packages/tornado/web.py", line 1704, in _execute
result = await result
File ".../site-packages/tornado/gen.py", line 775, in run
yielded = self.gen.send(value)
File ".../site-packages/notebook/services/contents/handlers.py", line 120, in get
self._finish_model(model, location=False)
File ".../site-packages/notebook/services/contents/handlers.py", line 91, in _finish_model
self.set_header('Last-Modified', model['last_modified'])
File …
=> Set a `last_modified` value on directory models if absent.

tiledbcontents/tiledbcontents.py
The good: In change #61 I pulled out `fill_in_dates`. Unfortunately,
I also forgot to actually *call it* from the old call site.
=> Restore `fill_in_dates` to returning directory model.

tiledbcontents/models.py
Previously, we learned that Jupyter REALLY REALLY WANTS to know the
creation and modification dates of every single thing it touches
and is NOT satisfied with being told that said information simply
does not exist. So we decided to just tell it "OK, the time is now.
Are you happy?" And initially, it did seem happy! We could successfully
browse and open and all the file operations we love to do so much,
so far as we could tell. But then, we found out that there were,
in fact, Problems.
Jupyter (sensibly) uses the last-modification date to check for edit
races, so that if you make a change but the file changes out under you
(i.e., its edit date changes since the time that you opened it),
it gives you a warning that you may be overwriting others' changes.
Given that we were always telling …
=> Use a long-ago date when filling in missing datetimes.

tiledbcontents/paths.py
Jupyter lies about the fact that it strips slashes (it does, sometimes),
and the way local `jupyter lab` behaves appears to be different from the
way it acts when running in jupyterhub.
=> Strip paths when seeing if they're local or remote.

tiledbcontents/arrays.py, tiledbcontents/caching.py, tiledbcontents/paths.py, tiledbcontents/tiledbcontents.py
This updates the caching layer to only cache metadata rather than also
holding onto array contents and an opened Array. This is because,
empirically, jupyter (no longer?) does a read immediately after a write,
which was the rationale for caching notebook contents.
Instead, we only open the array as needed to read/write it, and load
and update metadata at those times. This (and some other functions)
now run in an async-aware manner, putting only the blocking I/O onto
a worker thread and managing all other data in the main event loop.
=> Simplify caching layer and make it async-aware.

tiledbcontents/tiledbcontents.py
The [`Async`]`FileContentsManager` uses a special static content handler to handle file downloads that does not interact with the Jupyter contents manager at all. This meant that when we subclassed it, requests for file downloads (which work differently for requests for notebook contents, because ???) would be intercepted before they even hit the rest of Jupyter meaning that it was nigh impossible to figure out what was going on because even when you did a download, no request would appear in the server-side request logs on stderr.
After way too much digging I eventually figured out about the default files handler class:
https://github.com/jupyter-server/jupyter_server/blob/afb1af03bb17df59ddd1d29ba6baf6be6678d0d3/jupyter_server/services/contents/filemanager.py#L80-L86
and that this is …
=> Make downloading work right (again? for the first time?)

tiledbcontents/caching.py
Use a large value for per_page so we can list all notebooks in one go. This optimizes performance and solves a correctness issue that we were assuming only a single page of results.
=> Listing notebooks should be single page

tiledbcontents/arrays.py
This is about the s3 uri for array creation. In production the UI always sets it explicitly using the granular paths if specified, otherwise it fallsback to the default s3 path.
In development the the default s3 path is always used ignoring the granular paths. This commit uses the granular paths for dev.
=> Use the show granular storage paths if a path is not explicitly set

tiledbcontents/caching.py
The cached array class should also use timestamp writes to ensure metadata and fragments have the same timestamps for updates.
=> Update caching to use timestamp

tiledbcontents/caching.py, tiledbcontents/paths.py, tiledbcontents/tiledbcontents.py
This reads the fragment timestamps of writes to the array to assemble the list of checkpoints the user can restore to.  Checkpoint IDs are generated (and parsed) based on the timestamp in a human-readable YYYY-MM-DD HHhMM[mSS[sSSS]] format (without showing unnecessary precision when there is no ambiguity).
Verified working in a Jupyter Lab installation.
Context: sc-30786
=> Enable using TileDB array timestamps for remote checkpoints.

setup.py, tiledbcontents/arrays.py, tiledbcontents/async_tools.py, tiledbcontents/caching.py, tiledbcontents/call_server.py, tiledbcontents/listings.py, tiledbcontents/paths.py, tiledbcontents/tiledbcontents.py
This change creates the `call_server` module and an async layer atop it to delegate all operations which run against the core TileDB library out to a separate process which will never fork and just stays around.
This review also has a preliminary commit which only includes formatting fixes.
=> Run all operations which use TileDB Core in a separate process.

tiledbcontents/async_tools.py, tiledbcontents/tiledbcontents.py
Because some code works with TileDB core in a non-obvious manner, or a TileDB core object may be pickled across the wire and unpickled, this provides an extra layer of protection against accidentally instantiating a TileDB core object and thus breaking terminals.
---
Based on [a suggestion in the previous review](https://github.com/TileDB-Inc/TileDB-Cloud-Jupyter-Contents/pull/94#discussion_r1297303985). This handles it on the client side without affecting the generality of the call client/server architecture itself. We can use the rest of `async_tools` without poisoning TileDB, or poison TileDB without using the rest of `async_tools`.
I have also verified that this correctly breaks unpickling in addition to user instantiation with `tiledb.open` or similar functions.
=> Add code to "poison" TileDB core in the contents manager.

tiledbcontents/caching.py
When deserializing a notebook listing response from TileDB Cloud, it is possible that the generated client code handles the zero-array case by setting the `arrays` value to `None` rather than an empty iterable. This would cause a `NoneType is not iterable` exception.
I'm not *certain* if this is the case, but it's a guess.
=> Handle getting `None` arrays back from TileDB Cloud.
